### ISSUE TITLE
All list items and list are recreated when ReorderableList is re-rendered

### ISSUE THREAD

**Issue by grassick** [mWater/react-library#24]
Something is going wrong that causes the list and all items to be recreated instead of re-rendered when the list is re-rendered.

For example, when a map layer is changed, it immediately collapses since its state is wiped out. Also, on re-render, the list gets a new uuid, when it should stay the same.

**Comment by broncha** [comment]
Hi,

I dont think the items are being recreated. If you change the name of the the layer and reorder name stays the same. Also I could not reproduce the collapsing of the layer editor. The drag handle is only available if the layer editor is collapsed. 
I added 2 layers, collapsed one and reordered it below the open one, the latter one did not collapse.

About the id, last commit may have caused id.

```
-    @setState(listId: if @props.listId then @props.listId else uuid.v4())
+    @setState(listId: if nextProps.listId then nextProps.listId else uuid.v4())
```

I will revert this.

**Comment by broncha** [comment]
I see it now, was using the different pane. Looking at it now

**Comment by grassick** [comment]
Thanks. It's just a recreate without loss of data, but it does lose state (bad) and makes everything slower.
