### ISSUE TITLE
Nested modals do not display correctly

### ISSUE THREAD

**Issue by grassick** [mWater/react-library#3]
We use ModalPopupComponent but they currently do not nest correctly, nor does Bootstrap support it. Notice that the faded background does not over the outer modal correctly.

See demo (`gulp watch` from updated master branch).

We should display the parts (modal-backdrop + modal + adding `modal-open` class to body) manually rather than depend on the jquery code we have now:

```
      $(@modalNode).children().modal({ 
        show: true, 
        backdrop: "static", 
        keyboard: false 
        })
```

However it works instead, it should be able to support any number of nested modals and still work fine. Modals need to be rendered right under body tag to prevent clipping, hence the complexity of the ModalPopupComponent code.

**Comment by broncha** [comment]
I am still confused about the usage of the component. 
How are we using it?
To have modals you have to have a control that will open the modal.

The react overlay example , `<ModalExample>` renders a trigger and wrap the contents inside `<Modal>`

Shouldn't we be doing the same? `<ModalComponent>` renders a trigger with the children wrapped inside `<Modal>`. I suppose in most of our use case, we want to have a button or anchor that fires up the modal

**Comment by grassick** [comment]
Right, we have a control that somehow decides to render a modal or not, depending on state. They get nested when something inside the modal also decides it needs a modal and renders one.

I'm not sure what you mean by trigger... we can have a button that alters state and then renders the ModalPopupComponent. The example just always shows them, but it would never really be used like that.
