### ISSUE TITLE
Modal doesn't resize in some cases

### ISSUE THREAD

**Issue by grassick** [mWater/react-library#31]
![image](https://cloud.githubusercontent.com/assets/1238335/17627898/e7982c6c-6080-11e6-8262-7fd7c7d72022.png)

Go to portal.mwater.co/#datagrids

Pick Water Point, flip to filter tab. Then click on the box. It puts a scroll bar instead of making the modal bigger.

**Comment by broncha** [comment]
@grassick I just hit this too while working on expressions for ImageWidgetComponent.
This one is really tricky as the dropdown is absolutely positioned. I tested with bootstrap collapse and it stretches the modal body as expected. 

Working on a fix for absolutely positioned elements.

**Comment by broncha** [comment]
The fix for scrolling modal body is a blocker to fix this one. We added `overflow: auto` to modal body which makes the dropdown to actually scroll. If we remove `overflow:auto` the dropdown will pop out of the modal.

**Comment by broncha** [comment]
After 29dd8d6acea1bc44223e8f7cede0673127cfd032. it looks like this
![screen shot 2016-08-25 at 4 03 59 pm](https://cloud.githubusercontent.com/assets/46905/17966169/fa1efcb2-6adf-11e6-8a76-1f094d0141c2.png)
